### ISSUE TITLE
Undisclosed dependencies should be listed using requirements.txt

### ISSUE THREAD

**Issue by sachahjkl** [scottvr/wadzilla#1]
I suggest you add a `requirements.txt` file mentioning that  `BeautifulSoup4` and `requests` need to be installed for your program to work.

Useful resources:
- https://pip.pypa.io/en/stable/reference/requirements-file-format/
- https://www.geeksforgeeks.org/how-to-create-requirements-txt-file-in-python/

Example `requirements.txt` I got after running `pip freeze > requirements.txt`:

```
beautifulsoup4==4.12.3
certifi==2024.2.2
charset-normalizer==3.3.2
idna==3.7
requests==2.32.3
soupsieve==2.5
urllib3==2.2.1
```

**Comment by scottvr** [comment]
Yeah, I planned to eventually get to this but in the mean time I did mention in the README as Requirements. As you likely know, just installing BeautifulSoup and requests will install the others listed in your offered requirements.txt. In any case, it is a valid suggestion, as that's a more pythonic approach than forcing people to read the readme. ;-) Thanks for this. I'll leave it open until I commit a requirements.txt

**Comment by scottvr** [comment]
> [main 9656dcc] add requirements.txt
 1 file changed, 2 insertions(+)
 create mode 100644 requirements.txt
...
To https://github.com/scottvr/wadzilla.git
   bb12b80..8b0b350  main -> main
